import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {ReactNode} from "react";
import {ThemeProvider} from "@/components/providers/theme-provider";
import Providers from "@/components/providers/provider";
import {CookieConsent} from "@/modals/CookieConsent";
import BaseToast from "@/components/ui/toast/baseToast";
import BaseToastContainer from "@/components/ui/toast/baseToastContainer";
import {NewsletterConsent} from "@/modals/MarketingConsent";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "MailEngine",
    description: "Generated by codedbyaweto",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html
            lang="en"
            suppressHydrationWarning
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
        <head>
            <link rel="icon" href="/images/logo4.png" />
        </head>
        <body className="min-h-full flex flex-col">

        <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem={false}
            disableTransitionOnChange
        >

            <Providers>
                {children}
            </Providers>
            <NewsletterConsent />
            <CookieConsent />
            {/*<BaseToastContainer />*/}
        </ThemeProvider>

        </body>
        </html>
    );
}
