export enum BaseEnum {
    RESPONSE_CODE_SUCCESS = "00",
    RESPONSE_CODE_ERROR_BAD_REQUEST = "106",
    RESPONSE_CODE_UNAUTHORIZED = "22",

    // Auth response codes
    RESPONSE_CODE_ACCESS_TOKEN_EXPIRED = "112",
    RESPONSE_CODE_INVALID_REFRESH_TOKEN = "118",
}
