export const ImgLinks = {
    Logo1: "/images/logo5.png",
    Logo2: "/images/logo4.png",
    Logo3: "/images/logo.png",
    Logo4: "/images/KUCOIN.png",
    Logo5: "/images/Google_2015_logo.svg.png",
    Logo6: "/images/Amazon.webp",
    Logo7: "/images/spotify.png",
    Logo8: "/images/LinkedIn_logo.svg",
    Logo9: "/images/Netflix.svg",
    Logo10: "/images/Qualcomm-Logo.svg.png",
    Logo11: "/images/Netlify.png",
    Logo12: "/images/Youtube.svg",
    Logo13: "/images/qucoon-logo-1.png",
    img1: "/images/img1.avif",
    img2: "/images/img2.avif",
    img3: "/images/img3.avif",
    img4: "/images/img4.avif",
    img5: "/images/img7.avif",
    img6: "/images/img8.avif",
    img7: "/images/img20.jpg",
    img8: "/images/img21.webp",
    img9: "/images/img22.jpg",
}